tcort/markdown-link-check

markdown-link-check, package.json
- return exit code 1 when  dead links found
- update dependencies
example for dead link linting via npm script: [node-developer-boilerplate](https://github.com/ellerbrock/node-developer-boilerplate/blob/master/package.json#L38)
=> return exit code 1 when dead links found

markdown-link-check
set basePath for local files to directory that contains the file
it is required for checking local markdown files that have links to other local files as there is no way to pass basePath from the CLI
and without the basePath it would crash with:
```
url.js:95
throw new TypeError('Parameter "url" must be a string, not ' + typeof url);
^
TypeError: Parameter "url" must be a string, not undefined
at Url.parse (url.js:95:11)
at Object.urlParse [as parse] (url.js:89:5)
at linkCheck (node_modules/link-check/index.js:19:68)
at node_modules/markdown-link-check/index.js:16:9
at node_modules/async/dist/async.js:1008:9
at replenish (node_modules/async/dist/async.js:882:17)
at node_modules/async/dist/async.js:886:9
at _asyncMap (node_modules/async/dist/async.js:1006:5)
at Object.mapLimit …
```
=> set basePath for local files

README.md, index.js, package.json
Adds a progress bar to notify user about status, similar to following:
```
markdown-link-check https://github.com/tcort/markdown-link-check/blob/master/README.md -p
Checking... [=========================] 100%
[✓] http://example.com
[✓] https://github.com/tcort/markdown-link-check/blob/master/README.md
```
Only shows a progress bar:
- If running via command line
- And `-p` or  `--progress` switch is passed as an argument
Why?
- Helpful when its processing files with many links
- Good UI practice
Bumped up patch in `package.json`. All tests are passing, let me know if this needs modifications.
Thanks.
=> Added command line switch to show progress

markdown-link-check
Currently when you run the command utility, if there are no hyperlinks, there is no onscreen output. 
This PR adds a the message `No hyperlinks found` for such cases.
Test Report:
```bash
$ npm test
> markdown-link-check@3.1.1 pretest /home/user/Documents/learning/OpenSource/markdown-link-check
> jshint index.js markdown-link-check
> markdown-link-check@3.1.1 test /home/user/Documents/learning/OpenSource/markdown-link-check
> mocha -R spec
markdown-link-check
✓ should check the links in sample.md (470ms)
✓ should check the links in file.md
✓ should handle thousands of links (this test takes up to a minute) (9858ms)
3 passing (10s)
```
=> Added console message to show when there are no hyperlinks

README.md
The added `-exec echo "File: {}" \;` section prints the file name so that you can tell which file errors are coming from.
=> Update documentation: better recursive command

README.md
Doesn't need echo filename command anymore for the latest version.
=> Updated recursive folder command

markdown-link-check
When running with `--quiet` this message should probably be suppressed
=> fix: Don't show 'No hyperlinks found!' when quiet

README.md, index.js, markdown-link-check, test/markdown-link-check.test.js, test/sample.md
I need to support the following two platform specific scenarios (and tried to solve it in a generic way):
1. `[name](.attachments/name.ext)` (also with images)
2. `[name](/some/path/from/root/doc.md)`
We're using the VSTS Wiki and the behavior of the Web UI is to place all uploaded files (including images) into an `.attachments` folder sitting in the root directory.
The 2nd scenario comes into play when you want to reference Markdown documents ("pages") from the Wiki and use the "Copy page path" feature of the Web UI.
Both scenarios can be handled with the proposed solution (e.g. for scenario 2 replacing `"^//"` with the root directory like `file://...`) as well as other potential platform specific conventions.
______________________________________________________
I don't want to make it …
=> Replacement patterns to support platform specific conventions

markdown-link-check
=> fixes Invalid argument errors

README.md, markdown-link-check
For resolving parts of #35 (showing detailed status and error information)
Sample output:
```
node markdown-link-check -v ../performance.md
FILE: ../performance.md
[✖] ./images/sql-q1uery-reporting.png → Status: 400 Error: ENOENT: no such file or directory, access '/mnt/folder/images/sql-q1uery-reporting.png'
[✓] https://www.google.com → Status: 200
[✓] https://www.microsoft.com → Status: 200
[✖] https://github.com/tcort/markdown-link-check/blob/master/READMEeeeeeeee.md → Status: 404
[✖] https://githuuuuuuuuuuuuuuub.com/tcort/markdown-link-check/blob/master/READMEeeeeeeee.md → Status: 0 Error: getaddrinfo ENOTFOUND githuuuuuuuuuuuuuuub.com githuuuuuuuuuuuuuuub.com:443
[✖] https://giiiiithub.com/tcort/markdown-link-check/blob/master/README.md → Status: 0 Error: getaddrinfo ENOTFOUND …
```
=> adds verbose mode for showing detailed error information

markdown-link-check
Should fix this:
```
TypeError: Cannot read property 'F_OK' of undefined
at Command.<anonymous> (/usr/local/lib/node_modules/markdown-link-check/markdown-link-check:63:46)
at Command.listener (/usr/local/lib/node_modules/markdown-link-check/node_modules/commander/index.js:315:8)
at emitOne (events.js:77:13)
at Command.emit (events.js:169:7)
at Command.parseArgs (/usr/local/lib/node_modules/markdown-link-check/node_modules/commander/index.js:653:12)
at Command.parse (/usr/local/lib/node_modules/markdown-link-check/node_modules/commander/index.js:474:21)
at Object.<anonymous> (/usr/local/lib/node_modules/markdown-link-check/markdown-link-check:74:4)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
```
=> Fix accessing fs.constants.F_OK

markdown-link-check
This patch fixes several typos in error message were `valid` was `vaild`
=> fix(typo): fix typos in error messages

README.md, index.js, markdown-link-check, package-lock.json, test/file.md
Adds support for disable comments (similar to the ones in eslint).
`` disables markdown link check.
`` reenables markdown link check.
`` disables markdown link check for the next line.
`` disables markdown link check for this line.
The parameter ignoreDisable was added to ignore disable comments.
=> Add support for disable comments

markdown-link-check
- Show number of dead links found
- Make it easier to see dead link URLs when link check finishes by
grouping them at end of output
=> Surface dead links in results output

package.json
Hi,
First, thanks for your work! 
I've made a fix to remove unnecessary files from the published package on [npmjs](https://www.npmjs.com/).
- Here is the content of the published package before the fix (`npm pack --dry-run`):
```
npm notice
npm notice 📦  markdown-link-check@3.8.0
npm notice === Tarball Contents ===
npm notice 272B   Dockerfile
npm notice 5.9kB  markdown-link-check
npm notice 19.2kB test/hello.jpg
npm notice 3.5kB  index.js
npm notice 6.2kB  test/markdown-link-check.test.js
npm notice 1.8kB  package.json
npm notice 1.4kB  CHANGELOG.md
npm notice 248B   CONTRIBUTING.md
npm notice 432B   test/file.md
npm notice 766B   LICENSE.md
npm notice 5.8kB  README.md
npm notice 780B   test/sample.md
npm notice 57B    .travis.yml
npm notice === Tarball Details ===
npm notice name: …
```
=> Remove unnecessary files in the package published to npmjs

README.md, index.js, markdown-link-check, test/markdown-link-check.test.js, test/sample.md
- http 429 code retry option.
The link-check library used to check links here have this option but it defaults to disabled. I added a CLI option (`-r` or `--retry`) and also the ability to add the option to the JSON config file.
- option to define the http codes for which an `alive` status is returned. I did not only make 206 work, but any code and it's configurable. Default is 200 only.
CLI option and JSON config options are available. In JSON the list of codes has to be an integer array, on the command line a list with values separated by commas.
- test suite was updated to check for 206codes to be considered alive and for retry on 429 with a duration returned by headers. 
- no CLI test are already present in the library so I did not add any. Maybe a TODO...
- CLI help updated
- README …
=> Make http 429 and 206 codes return `alive`

README.md
Fixes #67 
Fix docker command in the readme file. Use volume instead of piping seems both work on linux & windows.
@NicolasMassart thx for the project.
Could you please check this?
=> Fix docker command in the readme

Dockerfile
Related to #110, but general image clean up.
* Use `node:alpine` image; the previous image `node:latest` is quite large (973 M) and provides no benefit above `node:alpine` (143 MB) for repo purposes.
* Transition to [Open Container Image Annotation spec](https://github.com/opencontainers/image-spec/blob/master/annotations.md) for image labels.
* Copy `package-lock.json` into environment.
* Remove `npm ls` from build as it clutters output and doesn't provide direct benefit.
* Image debugging is easier with:
```
docker run --rm -it --entrypoint /bin/sh <image>
```
* Additional labels (version, created) should be added at build time.
=> Update Dockerfile to ready image for public distribution

package-lock.json, package.json
fixes related to handling of 429 HTTP errors
fixes #114
=> update link-check dependency to 4.5.2

.github/workflows/docker.yml, .github/workflows/release.yml
Addresses Docker Image portion of #110.
* Create Docker workflow that builds images on each push/pull request and comments on commits with link
* Build and tag docker images on a new release (tagged latest, stable, semver)
The workflows associated with this PR use the GitHub Container Registry (GitHub Package Docker Registry will sunset next year). GCR requires a Personal Access Token with the `package:write` permission to push images.
The workflows use the PAT in form of a secret called `PUBLISH_TOKEN`. **Prior to merge**, a PAT with `package:write` should be created and stored in the repository secrets as `PUBLISH_TOKEN`.
[Creating a personal access token - GitHub Docs](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token) …
=> Add Docker build and Release workflows via Github workflows

README.md, markdown-link-check, test/markdown-link-check.test.js
Since there are two new parameters in [link-check](https://github.com/tcort/link-check) latest version(`retryCount` and `fallbackRetryDelay`), I think it's a good idea to add them here, too.
=> Add support for retryCount and fallbackRetryDelay

.github/workflows/docker.yml, .github/workflows/release.yml
Old mode deprecated for security reasons (https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/)
=> Switch to the new Github Actions environment variable idiom

README.md
Fixes #134 
I found this to be set in the `link-check` repository, so I copied the same description and added it to the:
- API docs
- Command line tool and config example
Let me know if I should add a test that takes in different types of input (2s, 1d, etc.).
=> doc: timeout option to API calls and config file

CHANGELOG.md, README.md
* Add **Other tools** section in README + [Mega-Linter](https://nvuillam.github.io/mega-linter/)
Split of https://github.com/tcort/markdown-link-check/pull/137 , as requested
=> Add Other Tools & Mega-Linter link

README.md, index.js, markdown-link-check, test/local-file.md, test/markdown-link-check.test.js
This PR allows to use `{{BASEURL}}` as a variable in the replacement patterns to be replaced during execution with the `opts.baseUrl`. This allows to write generic config files, which work also for local reference checks of URL. 
For example following config can be now used to check that all urls starting with `/` are resolvable from the project/repository root (when someone runs markdown-link-check) in the repository root). This is helpful as e.g. github renders `/` urls relative to the repository url in the UI and not relative to github.com completely. 
```json
{
"replacementPatterns": [
{
"pattern": "^/",
"replacement": "{{BASEURL}}/"
}
]
}
```
fixes #16 
fixes #120
=> add {{BASEURL}} as replacement pattern

index.js, test/markdown-link-check.test.js, test/special-replacements.md
This PR introduces a special replacement pattern ```{{env.<env_var_name>}}``` for environment variables, that can be used in httpHeaders and in pattern replacement strings. From my point of view it fixes the problem mentioned in #103.
Once merged, credentials can be passed to markdown-link-check via env vars.
```json
{
...
"httpHeaders": [
{
"urls": ["https://example.com"],
"headers": {
"Authorization": "Bearer {{env.EXAMPLE_COM_TOKEN}}",
"Foo": "Bar"
}
}
],
...
}
```
=> support of environment variables in httpheaders and replacement patterns

.github/workflows/release.yml
I generated a new npm access token (the "automation" kind), added the secret to the repository, and updated `release.yml`. 
I'm not too familiar with github actions, so please have a look to ensure I did it properly. If everything is OK, I'll repeat for `tcort/link-check` and `tcort/markdown-link-extractor` projects.
Relevant Documentation:
- https://github.com/actions/setup-node
- https://docs.github.com/en/free-pro-team@latest/actions/guides/publishing-nodejs-packages
=> release.yml: Create a GH action to publish on NPM repos #153

Dockerfile
This makes it easier to use the tool from within the Docker image, for
example when the image is used as environment for a CI job.
=> Symlink executable into PATH

.pre-commit-hooks.yaml
Closes #169.
Add a ` .pre-commit-hooks.yaml` file which allows using `markdown-link-check` as a [pre-commit](https://pre-commit.com) hook.
=> Add pre-commit support

markdown-link-check
Output is difficult to visually parse when no color is available, such as when looking at GitHub Actions logs using [github-action-markdown-link-check](https://github.com/gaurav-nelson/github-action-markdown-link-check).
This should make it much easier to visually divide the logs according to what file they pertain to. This is what it looks like in my console:
=> Indent console output for each file

markdown-link-check
Resolves #78
This is an improved version of #178.
Although the diff is large, since I split commits into small units, I suppose you can understand what I changed by seeing each commit.
```sh-session
$ git clone git@github.com:kenji-miyake/markdown-link-check.git -b support-multi-inputs
$ cd markdown-link-check
$ git cherry-pick 7b3ad2c1ce5e49d03ff29cbebd6951006b0ccf4a
$ # pre-commit
$ pre-commit clean
$ pre-commit run -a
[WARNING] The 'rev' field of repo '.' appears to be a mutable reference (moving tag / branch).  Mutable references are never updated after first install and are not supported.  See https://pre-commit.com/#using-the-latest-version-for-a-repository for more details.  Hint: `pre-commit autoupdate` often fixes this.
[INFO] Initializing environment for ..
[INFO] Installing …
```
=> feat: support multi inputs

markdown-link-check
I'm sorry I made a mistake when I supported multiple inputs in #179.
Since `baseUrl` is different depending on files, I had to set it for each file.
@tcort Although this might not be a clean implementation, could you review it? :pray:
=> fix: set baseUrl for each file

test/hash-links.md, test/markdown-link-check.test.js
It seems https://github.com/tcort/markdown-link-check/commit/65221868bb1101bf211f9791037f304eacf908a2 caused a regression with inline `<a>` links.
Trying to see if this is intentional, currently I've only included a unit test to discuss whether the behavior is intentional or not (without including the actual "fix").
=> Fix the anchor regression

.github/workflows/ci.yml, .github/workflows/release.yml
- no `fail-fast` for build
- drop 18.x for now
cc @tcort
=> ci: fix build and drop 18.x

markdown-link-check
Closes issue https://github.com/tcort/markdown-link-check/issues/223
```text
$ ./markdown-link-check test/* --quiet
FILE: test/file.md
FILE: test/hash-links.md
[✖] #potato
[✖] #tomato
4 links checked.
ERROR: 2 dead links found!
[✖] #potato → Status: 404
[✖] #tomato → Status: 404
FILE: test/hello.jpg
0 links checked.
FILE: test/local-file.md
FILE: test/markdown-link-check.test.js
0 links checked.
FILE: test/sample.md
FILE: test/special-replacements.md
```
```text
$ ./markdown-link-check test/* --quiet
ERROR: 2 dead links found in test/hash-links.md!
[✖] #potato → Status: 404
[✖] #tomato → Status: 404
```
```text
$ ./markdown-link-check test/file.md --quiet
FILE: test/file.md
```
```text
$ ./markdown-link-check test/file.md --quiet
$
```
=> fix: make --quiet flag only output errors

.github/dependabot.yml, .github/workflows/ci.yml
Add Dependabot to send PRs for NPM and GitHub Action dependency updates.
Skips double building for when Dependabot pushes it's branches, since they only land through PRs
=> chore: Add Dependabot for version updates

.github/workflows/release.yml
Noticed because it was getting flagged in VS Code against the schema validation it has from one of the extentions
=> ci: Use array for release type schema

.eslintrc.js, index.js, package-lock.json, package.json, test/markdown-link-check.test.js
ESLint is much more actively maintained these days. There are probably a few other plug-ins that could be added, but this was a quick convershion as a start
=> chore: Convert JSHint to ESLint

markdown-link-check
The options passed as command line arguments were ignored. Fixes issue #248 and #246.
=> fix:Config-file-and-others-options-ignored

markdown-link-check, package-lock.json, package.json
Uses [proxy-agent](https://www.npmjs.com/package/proxy-agent) to support load md files via proxies via env vars.
Needle has no good proxy implementation. (https://github.com/tomas/needle/issues/406)
Related to:
- https://github.com/tcort/link-check/pull/70
Part of:
- https://github.com/tcort/markdown-link-check/issues/166
=> Add support to load md files via proxy

markdown-link-check
`url.parse` is deprecated, `new URL` is supported since Node v10.
=> refactor: replace url.parse with new URL

README.md, index.js
Closes #276 by adding a new option (`"global": true`) to avoid possible breaking changes.
=> feat: add global option to replacementPatterns

markdown-link-check
Add a basic ignore subpaths argument. just checks if paths include it, no regex/glob/etc yet. Closes #102.
=> feat: add basic ignore subpaths argument

.github/workflows/ci.yml
Since Node 18 github action uses IPv6 (host: ::1). This should in url: [::1].
But any used lib seems to be incompatible.
Replaces:
- #294
Related:
- #295
Fixes:
- #291
=> fix failing github action with IPv6

README.md
Update status badge
It seems that the URL has been changed: https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge#using-the-workflow-file-name
Related:
- #291
=> fix status badge in README

test/markdown-link-check.test.js
Enable tests for hash links and adds missing result for (broken, added by https://github.com/tcort/markdown-link-check/commit/c4068d7fe317e2c8414bcc49a770d9b7b38c6810) `#header-with-special-char-`.
Revert https://github.com/tcort/markdown-link-check/commit/98ba6bfd6d14147a7d63e9f52ad6352428a400e6
At the moment the pipeline is failing because of current broken release.
It shows the failure reason for
- #304
=> enable skipped tests for hash links

index.js, markdown-link-check, test/markdown-link-check.test.js, test/section-links.md
Extract markdown heading lines and convert to section link names, check all section links against this list and return a 404 for any that do not have a heading.
Filter out code blocks because comments can be false positives for markdown headers.
Make some minor adjustments for the tests to pass on Windows.
Fix #250
=> Check GitHub markdown section links

README.md
=> docs: add example for GitLab pipeline

index.js, test/hash-links.md, test/markdown-link-check.test.js
Allows you to check and use unicode characters in anchor links (e.g. german umlauts or emojis)
follow up / improvement of:
- #312 
fixes:
- #325
- #358
- #348
- #360
probably fixes:
- #337
parts are based on:
- [anchor link handling](https://github.com/Moonbase59/gh-toc/blob/222135269ed1990d3d79c3b8d7ce1594a35966ea/gh-toc.js#L156-L174)
- [parsing markdown links](https://davidwells.io/snippets/regex-match-markdown-links)
- [Regex docs](https://ruby-doc.org/3.3.2/Regexp.html#class-Regexp-label-Unicode+Character+Categories)
- [similar to markdownlint](https://github.com/DavidAnson/markdownlint/blob/b2305efafb034b1f328845aec9928b5363ffd646/lib/md051.js#L45)
also added some tests
=> feat: add support for unicode characters in anchor links

package-lock.json, package.json
I did a check with: `npx npm-check`
and get:
`@eslint/js    😟  PKG ERR!  Not in the package.json. Found in: /eslint.config.mjs`
Reason:
- #318
=> fix: add used `@eslint/js` to dev dependencies in package.json

.pre-commit-hooks.yaml
Currently I see
```
[WARNING] repo `https://github.com/tcort/markdown-link-check` uses deprecated stage names (commit, push) which will be removed in a future version.  Hint: often `pre-commit autoupdate --repo https://github.com/tcort/markdown-link-check` will fix this.  if it does not -- consider reporting an issue to that repo.
```
When using this hook. I think, based on [this](https://pre-commit.com/#confining-hooks-to-run-at-certain-stages) (and specifically the note `new in 3.2.0: The values of stages match the hook names. Previously, commit, push, and merge-commit matched pre-commit, pre-push, and pre-merge-commit respectively.`) that this will fix that warning. I've allowed edits to this branch, so feel free to edit yourself or request changes!
Thank you for making this hook, it …
=> Update hook names

README.md, markdown-link-check
Allow scan of directories like `./docs/` and also globs like `/**/*.md`. Also supports ignoring files/directories.
fixes:
- #40 
one part from:
- #289
> processing folders as inputs (folder is processed recursively)
=> feat: support iterate link check over directories in CLI

index.js, test/hash-links.md, test/markdown-link-check.test.js
Extracts all html tags with the attribute `id` and all `a` tags with the attribute `name` and allows them as valid section links.
Ignore:
- code blocks (` ``` `)
- single code (`` ` ``)
- html comments
Fits the lint rule [MD51](https://github.com/DavidAnson/markdownlint/blob/main/doc/md051.md)
> Alternatively, any HTML tag with an `id` attribute or an `a` tag with a `name` attribute can be used to define a fragment
fixes:
- #202
- #195 
related to:
- #328
=> feat: anchor link checks support HTML tags like `<a name="foo"></a>`

.github/workflows/ci.yml
Nodejs 21 is EoL: https://endoflife.date/nodejs
=> ci: bump nodejs

markdown-link-check
Fix https://github.com/tcort/markdown-link-check/issues/369
=> Do not override reporter option if not defined in config file (issue #369)

README.md
- supersedes #374 (which I previously closed after waiting more than 2 months for a response)
The [README > Run using Docker](https://github.com/tcort/markdown-link-check/blob/master/README.md#run-using-docker) command example
```shell
docker run -v ${PWD}:/tmp:ro --rm -i ghcr.io/tcort/markdown-link-check:stable /tmp/README.md
```
uses `PWD` (Print Working Directory). The syntax `${PWD}` can now be replaced by a simpler one using relative paths.
The Docker documentation for [`docker container run`](https://docs.docker.com/reference/cli/docker/container/run/) (with alias `docker run`) describes the option [Mount volume (-v)](https://docs.docker.com/reference/cli/docker/container/run/#volume) using relative paths:
> As of Docker Engine version 23, you can use relative paths on the host.
>
> …
=> docs: migrate Docker instructions to relative bind mount

README.md
Seems to have drifted slightly.
=> docs: Update usage in README.md with output from --help

.github/CODEOWNERS
Hopefully this will result in @tcort, @smainil, @BaseMax and @WillGibson automatically being added to pull request reviewers.
=> chore(admin): Add CODEOWNERS file

.github/workflows/close-stale-issues-and-pull-requests.yml
I expect loads of the existing issues are no longer relevant as they apply to earlier versions etc.
This should help reduce the current (and ongoing) triage load.
=> chore(admin): Automate admin for stale issues and pull requests

README.md
- supersedes #373 which was closed due to no response
https://github.com/vercel/ms
> Use this package to easily convert various time formats to milliseconds.
The [README](https://github.com/tcort/markdown-link-check/blob/master/README.md) refers in several places to the npm package `zeit/ms` which does not exist in the npm registry.
[ZEIT is now Vercel](https://vercel.com/blog/zeit-is-now-vercel) describes that a rebranding took place in April 2020.
The GitHub repo link https://github.com/zeit/ms redirects to https://github.com/vercel/ms
The npm registry reports not found for https://www.npmjs.com/package/zeit/ms, whereas https://www.npmjs.com/package/ms links to the current Vercel repo https://github.com/vercel/ms.
Change reference to the npm package `zeit/ms` to …
=> docs: README rebrand npm package zeit/ms to ms

README.md
- closes https://github.com/tcort/markdown-link-check/issues/371
The [README](https://github.com/tcort/markdown-link-check/blob/master/README.md) introduces itself with the description:
> Extracts links from markdown texts and checks whether each link is alive (`200 OK`) or dead. `mailto:` links are validated with [isemail](https://www.npmjs.com/package/isemail).
The reference to [isemail](https://www.npmjs.com/package/isemail) is however no longer correct.
[markdown-link-check@3.13.7](https://github.com/tcort/markdown-link-check/releases/tag/v3.13.7) (current `latest`):
1. has no dependency on [isemail](https://www.npmjs.com/package/isemail)
2. delegates `mailto:` link checking to [link-check@^5.4.0](https://github.com/tcort/link-check/tree/v5.4.0) …
=> docs: remove reference to isemail - no longer used

README.md
Since you have forked the github action, I figured it would be simpler to just link to that one :)
=> docs: update link to maintained github action

.github/ISSUE_TEMPLATE/bug-report.yaml, .github/ISSUE_TEMPLATE/report-a-bug.yaml, .github/ISSUE_TEMPLATE/request-an-enhancement.yaml
Hopefully this will start to ensure that new issues arrive in a consistent format that will help ensure we have the required information to triage and investigate them.
=> chore(admin): Add issue forms

.github/workflows/close-stale-issues-and-pull-requests.yml
Hi @BaseMax @WillGibson ,
W all have a job in addition to managing this repo so I think that 30 days is definitely too short for automatic closing
Does it sounds good to you if we increase the number of days ?
=> ci: increase number of days before automatic closing
