tcort/markdown-link-check

- README.md
This would improve the readability in readme :)
> Enable syntax highlight in README.md code block

- README.md
as explained at https://github.com/tcort/markdown-link-check/issues/20#issuecomment-327200777
> make explicit how to check a folder recursively

- markdown-link-check
fixes #26 
Shows filenames in output. Following is a sample output.
<Details>
```
FILE: ./README.md
Checking... [=========================] 100%
[✓] https://opensource.microsoft.com/codeofconduct/
[✓] https://opensource.microsoft.com/codeofconduct/faq/
[✓] mailto:opencode@microsoft.com
[✓] https://docs.microsoft.com/bot-framework
[✓] contributor-guide/contributor-guide-index.md
[✓] #ways-to-contribute
[✓] #code-of-conduct
[✓] #about-your-contributions-to-Bot-Framework-content
[✓] #repository-organization
[✓] #use-github-git-and-this-repository
[✓] #how-to-use-markdown-to-format-your-topic
[✓] #more-resources
[✓] https://docs.microsoft.com/legal/termsofuse
[✓] contributor-guide/file-names-and-locations.md
[✓] contributor-guide/custom-markdown-extensions.md
[✓] …
```
> Adds filenames in command line output

- Dockerfile
> Add ENTRYPOINT for `docker run` commands.

- markdown-link-check
> Fix issue with fs constants

- markdown-link-check
Attempt to fix #60 
The read stream error handling logic should be discussed, as of now it's a bit rough and it exists if any errors happen. This might not be what users want. Feel free to comment if you  have suggestions on that. Moreover I don't think that PR releases resources the cleanest way possible so that might be necessary to log an issue and spend more time on this. As of now it should fix the project.
> Fix fs access anti pattern

- package-lock.json
- package.json
Resolves vulnerable dependencies as found by `npm audit`.
> Update npm files

- .github/workflows/ci.yml
> chore: Add GitHub Actions CI setup

- .github/workflows/docker.yml
- .github/workflows/release.yml
- README.md
- markdown-link-check
- test/markdown-link-check.test.js
> Timeout Option added

- README.md
fixes #110
should gate until #112 merged
> Update help text for docker image use (post mark of image public)

- .github/workflows/release.yml
I added a code review comment in #132 that suggested my patchset was incomplete, it must have gotten missed. This PR fixes what I broke when the the prior PR was merged.
* Fix SEMVER_TAGS environment variable set (really bungled that one)
* Remove unused FULL_SNAPSHOT_URL set
> Repair release.yml

- markdown-link-check
Related: #179
@tcort I'm so sorry I found one more mistake. :cry:
I had to wait for the config to be loaded before checking the links.
I've tested this in my local environment.
> fix: wait for config loaded

- .github/workflows/ci.yml
- .github/workflows/release.yml
- .travis.yml
- package-lock.json
- remove travis
- upgrade to use nodejs 18
- update action dependencies
cc @tcort
> build: remove travis, upgrade to use nodejs18

- test/hash-links.md
This PR adds a test to check if links to headlines containing special characters is working.
> tests: add test for link to a header with special character

- .github/workflows/ci.yml
Enable the caching with the setup-node Action too
> ci: Add current Node versions to matrix build

- README.md
@tcort how about this? To document @janosh #170 for #169.
I started looking into how to do this myself, and only then noticed by chance you already it - seems worth mentioning on the README!
BTW https://github.com/pre-commit/pre-commit.com/pull/802 FYI.
PS Can't wait for a new release which will include #230! 😃 
Thank You for maintaining this great project!
> docs: Add how to run as pre-commit to README

- markdown-link-check
fix https://github.com/tcort/markdown-link-check/issues/254
> fixed the error when there is no --config option

- .github/workflows/ci.yml
Adding tests across Mac/Linux/Windows to catch any path issues
> ci: Use matrix for cross-OS testing

- markdown-link-check
'url' is declared but its value is never read.ts(6133)
> fix: remove not used `const url`

- index.js
- package-lock.json
- package.json
Remove lodash and replace the function used with native function.
one part from:
- #289 
related to:
- #280
> chore(deps): remove lodash
